export const ROLES = {
  STUDENT: 'STUDENT',
  OFFICER: 'OFFICER',
  ADMIN: 'ADMIN',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const APPLICATION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  DOCUMENT_VERIFICATION: 'DOCUMENT_VERIFICATION',
  ADDITIONAL_DOCUMENTS_REQUIRED: 'ADDITIONAL_DOCUMENTS_REQUIRED',
  ELIGIBILITY_REVIEW: 'ELIGIBILITY_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export type ApplicationStatus = (typeof APPLICATION_STATUS)[keyof typeof APPLICATION_STATUS];

export const DOCUMENT_TYPES = {
  IDENTITY_PROOF: 'IDENTITY_PROOF',
  INCOME_CERTIFICATE: 'INCOME_CERTIFICATE',
  CASTE_CERTIFICATE: 'CASTE_CERTIFICATE',
  RESIDENCE_CERTIFICATE: 'RESIDENCE_CERTIFICATE',
  ACADEMIC_MARKSHEET: 'ACADEMIC_MARKSHEET',
  BANK_PROOF: 'BANK_PROOF',
  FEE_RECEIPT: 'FEE_RECEIPT',
  BONAFIDE_CERTIFICATE: 'BONAFIDE_CERTIFICATE',
  SCHOLARSHIP_FORM: 'SCHOLARSHIP_FORM',
  OTHER: 'OTHER',
} as const;

export type DocumentType = (typeof DOCUMENT_TYPES)[keyof typeof DOCUMENT_TYPES];

export const DOCUMENT_STATUS = {
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  REUPLOAD_REQUIRED: 'REUPLOAD_REQUIRED',
  EXPIRED: 'EXPIRED',
} as const;

export type DocumentStatus = (typeof DOCUMENT_STATUS)[keyof typeof DOCUMENT_STATUS];

export const TICKET_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_STUDENT: 'WAITING_FOR_STUDENT',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
} as const;

export type TicketStatus = (typeof TICKET_STATUS)[keyof typeof TICKET_STATUS];

export const TICKET_CATEGORIES = {
  SCHOLARSHIP: 'SCHOLARSHIP',
  DOCUMENTS: 'DOCUMENTS',
  ATTENDANCE: 'ATTENDANCE',
  ELIGIBILITY: 'ELIGIBILITY',
  RENEWAL: 'RENEWAL',
  TECHNICAL: 'TECHNICAL',
  OTHER: 'OTHER',
} as const;

export const CATEGORIES = ['GENERAL', 'SC', 'ST', 'OBC', 'EWS', 'MINORITY', 'PWD'] as const;

export const ATTENDANCE_THRESHOLDS = {
  SAFE_MINIMUM: 75,
  WARNING_MINIMUM: 65,
  CRITICAL_MINIMUM: 60,
};
